"""Add accepted_at to Booking

Revision ID: 02c149b0b72f
Revises: bedbc3a017f8
Create Date: 2026-07-03 11:23:20.652752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c149b0b72f'
down_revision = 'bedbc3a017f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('accepted_at')

    # ### end Alembic commands ###
