"""Add CorporateRequest model and corporate profile address fields

Revision ID: 08fc38061584
Revises: 953d61c1bbff
Create Date: 2026-07-01 22:05:28.659351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fc38061584'
down_revision = '953d61c1bbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporate_profile_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('budget_naira', sa.Integer(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("request_type IN ('procurement', 'facility_management', 'janitorial', 'other')", name='ck_corporate_requests_type_valid'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'cancelled')", name='ck_corporate_requests_status_valid'),
    sa.ForeignKeyConstraint(['corporate_profile_id'], ['corporate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_profiles', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    op.drop_table('corporate_requests')
    # ### end Alembic commands ###
