"""Add profile completion email tracking fields

Revision ID: 29784e0c7687
Revises: 2b191c18ca7f
Create Date: 2026-07-07 14:00:26.893883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29784e0c7687'
down_revision = '2b191c18ca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('welcome_email_sent_at', sa.DateTime(), nullable=True))
        # server_default backfills existing rows in this NOT NULL column -
        # the model's Python-level default= only applies to new inserts.
        batch_op.add_column(sa.Column('profile_reminder_stage', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('profile_reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_completion_congrats_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_completion_congrats_sent_at')
        batch_op.drop_column('profile_reminder_sent_at')
        batch_op.drop_column('profile_reminder_stage')
        batch_op.drop_column('welcome_email_sent_at')

    # ### end Alembic commands ###
