"""Add indexes for common filter/lookup columns

Revision ID: 6c1afcdd5c31
Revises: 712ebcdabb28
Create Date: 2026-07-02 07:57:01.375453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1afcdd5c31'
down_revision = '712ebcdabb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_customer_profile_id'), ['customer_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_professional_profile_id'), ['professional_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_one_id'), ['user_one_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_two_id'), ['user_two_id'], unique=False)

    with op.batch_alter_table('corporate_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_requests_corporate_profile_id'), ['corporate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professional_profiles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professional_profiles_is_verified'), ['is_verified'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_professional_profile_id'), ['professional_profile_id'], unique=False)

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_professional_profile_id'), ['professional_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_professional_profile_id'))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_professional_profile_id'))

    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professional_profiles_is_verified'))
        batch_op.drop_index(batch_op.f('ix_professional_profiles_category_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    with op.batch_alter_table('corporate_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_requests_status'))
        batch_op.drop_index(batch_op.f('ix_corporate_requests_corporate_profile_id'))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_two_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_user_one_id'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_professional_profile_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_profile_id'))

    # ### end Alembic commands ###
