"""Add Review model

Revision ID: 712ebcdabb28
Revises: 2d0f17a5240b
Create Date: 2026-07-02 07:15:36.498932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712ebcdabb28'
down_revision = '2d0f17a5240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
