"""Add Skill, PortfolioItem, Verification models and availability fields

Revision ID: 953d61c1bbff
Revises: 9a6cf4f1577d
Create Date: 2026-07-01 21:47:44.493979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953d61c1bbff'
down_revision = '9a6cf4f1577d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_verifications_status_valid'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_days', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('available_hours', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.drop_column('available_hours')
        batch_op.drop_column('available_days')

    op.drop_table('verifications')
    op.drop_table('skills')
    op.drop_table('portfolio_items')
    # ### end Alembic commands ###
