"""Add verified_at to ProfessionalProfile

Revision ID: b853e3410799
Revises: deafd9481e9e
Create Date: 2026-07-03 13:39:45.251266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b853e3410799'
down_revision = 'deafd9481e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###
