"""Add profile completion fields to ProfessionalProfile

Revision ID: deafd9481e9e
Revises: 02c149b0b72f
Create Date: 2026-07-03 12:04:54.214757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deafd9481e9e'
down_revision = '02c149b0b72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo_filename', sa.String(length=255), nullable=True))
        # server_default backfills the existing row(s) in this NOT NULL
        # column - the model's Python-level default= only applies to new
        # inserts, not to rows that already exist when this migration runs.
        batch_op.add_column(sa.Column('professional_type', sa.String(length=30), nullable=False, server_default='individual'))
        batch_op.add_column(sa.Column('business_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('business_registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_business_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('pricing_type', sa.String(length=30), nullable=False, server_default='not_specified'))
        batch_op.add_column(sa.Column('pricing_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_inspection', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('consultation_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guarantor_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('guarantor_relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guarantor_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guarantor_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.create_check_constraint(
            'ck_professional_profiles_type_valid', "professional_type IN ('individual', 'registered_business')"
        )
        batch_op.create_check_constraint(
            'ck_professional_profiles_pricing_type_valid',
            "pricing_type IN ('not_specified', 'starts_from', 'hourly', 'daily')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('ck_professional_profiles_pricing_type_valid', type_='check')
        batch_op.drop_constraint('ck_professional_profiles_type_valid', type_='check')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('guarantor_address')
        batch_op.drop_column('guarantor_phone')
        batch_op.drop_column('guarantor_relationship')
        batch_op.drop_column('guarantor_name')
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('requires_inspection')
        batch_op.drop_column('pricing_amount')
        batch_op.drop_column('pricing_type')
        batch_op.drop_column('is_business_verified')
        batch_op.drop_column('business_registration_number')
        batch_op.drop_column('business_name')
        batch_op.drop_column('professional_type')
        batch_op.drop_column('profile_photo_filename')

    # ### end Alembic commands ###
